name: Flutter Tag Build

on:
  workflow_dispatch:
    inputs:
      upload-tag:
        description: "Tag name (e.g. 1.4.9-1)"
        required: true
        default: "nightly"
      platforms:
        description: "Platforms to build"
        required: true
        type: choice
        options:
          - all
          - windows-only
          - windows-portable
          - linux-only
          - mac-only
          - android-only
        default: "windows-only"
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+-[0-9]+'

jobs:
  generate-bridge:
    if: inputs.platforms == 'all' || inputs.platforms == '' || github.event_name == 'push'
    uses: ./.github/workflows/flutter-build.yml
    secrets: inherit
    with:
      upload-artifact: true
      upload-tag: ${{ inputs.upload-tag || github.ref_name }}
      job-filter: "generate-bridge"

  build-RustDeskTempTopMostWindow:
    if: inputs.platforms == 'all' || inputs.platforms == '' || github.event_name == 'push'
    uses: ./.github/workflows/flutter-build.yml
    secrets: inherit
    with:
      upload-artifact: true
      upload-tag: ${{ inputs.upload-tag || github.ref_name }}
      job-filter: "build-RustDeskTempTopMostWindow"

  build-for-windows-flutter:
    if: inputs.platforms == 'all' || inputs.platforms == 'windows-only' || inputs.platforms == 'windows-portable' || inputs.platforms == ''
    uses: ./.github/workflows/flutter-build.yml
    secrets: inherit
    with:
      upload-artifact: true
      upload-tag: ${{ inputs.upload-tag || github.ref_name }}
      job-filter: "build-for-windows-flutter"

  build-for-windows-sciter:
    if: inputs.platforms == 'all' || inputs.platforms == '' || github.event_name == 'push'
    uses: ./.github/workflows/flutter-build.yml
    secrets: inherit
    with:
      upload-artifact: true
      upload-tag: ${{ inputs.upload-tag || github.ref_name }}
      job-filter: "build-for-windows-sciter"

  build-rustdesk-ios:
    if: inputs.platforms == 'all' || inputs.platforms == '' || github.event_name == 'push'
    uses: ./.github/workflows/flutter-build.yml
    secrets: inherit
    with:
      upload-artifact: true
      upload-tag: ${{ inputs.upload-tag || github.ref_name }}
      job-filter: "build-rustdesk-ios"

  build-for-macOS:
    if: inputs.platforms == 'all' || inputs.platforms == 'mac-only' || inputs.platforms == ''
    uses: ./.github/workflows/flutter-build.yml
    secrets: inherit
    with:
      upload-artifact: true
      upload-tag: ${{ inputs.upload-tag || github.ref_name }}
      job-filter: "build-for-macOS"

  publish_unsigned:
    if: inputs.platforms == 'all' || inputs.platforms == '' || github.event_name == 'push'
    uses: ./.github/workflows/flutter-build.yml
    secrets: inherit
    with:
      upload-artifact: true
      upload-tag: ${{ inputs.upload-tag || github.ref_name }}
      job-filter: "publish_unsigned"

  build-rustdesk-android:
    if: inputs.platforms == 'all' || inputs.platforms == 'android-only' || inputs.platforms == ''
    uses: ./.github/workflows/flutter-build.yml
    secrets: inherit
    with:
      upload-artifact: true
      upload-tag: ${{ inputs.upload-tag || github.ref_name }}
      job-filter: "build-rustdesk-android"

  build-rustdesk-android-universal:
    if: inputs.platforms == 'all' || inputs.platforms == 'android-only' || inputs.platforms == ''
    uses: ./.github/workflows/flutter-build.yml
    secrets: inherit
    with:
      upload-artifact: true
      upload-tag: ${{ inputs.upload-tag || github.ref_name }}
      job-filter: "build-rustdesk-android-universal"

  build-rustdesk-linux:
    if: inputs.platforms == 'all' || inputs.platforms == 'linux-only' || inputs.platforms == ''
    uses: ./.github/workflows/flutter-build.yml
    secrets: inherit
    with:
      upload-artifact: true
      upload-tag: ${{ inputs.upload-tag || github.ref_name }}
      job-filter: "build-rustdesk-linux"

  build-rustdesk-linux-sciter:
    if: inputs.platforms == 'all' || inputs.platforms == '' || github.event_name == 'push'
    uses: ./.github/workflows/flutter-build.yml
    secrets: inherit
    with:
      upload-artifact: true
      upload-tag: ${{ inputs.upload-tag || github.ref_name }}
      job-filter: "build-rustdesk-linux-sciter"

  build-appimage:
    if: inputs.platforms == 'all' || inputs.platforms == 'linux-only' || inputs.platforms == ''
    uses: ./.github/workflows/flutter-build.yml
    secrets: inherit
    with:
      upload-artifact: true
      upload-tag: ${{ inputs.upload-tag || github.ref_name }}
      job-filter: "build-appimage"

  build-flatpak:
    if: inputs.platforms == 'all' || inputs.platforms == '' || github.event_name == 'push'
    uses: ./.github/workflows/flutter-build.yml
    secrets: inherit
    with:
      upload-artifact: true
      upload-tag: ${{ inputs.upload-tag || github.ref_name }}
      job-filter: "build-flatpak"

  build-rustdesk-web:
    if: inputs.platforms == 'all' || inputs.platforms == '' || github.event_name == 'push'
    uses: ./.github/workflows/flutter-build.yml
    secrets: inherit
    with:
      upload-artifact: true
      upload-tag: ${{ inputs.upload-tag || github.ref_name }}
      job-filter: "build-rustdesk-web"
